name: CI Pipeline

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install pnpm
        run: npm install -g pnpm@^10.9.0
      
      - name: Setup pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

        # deploy-prod:
        #     if: github.ref == 'refs/heads/prod'
        #     needs: build-and-test
        #     runs-on: ubuntu-latest

        #     steps:
        #       - uses: actions/checkout@v4
        #       - uses: actions/setup-node@v4
        #         with:
        #           node-version: 20
        #           cache: pnpm

        #       - name: Install dependencies
        #         run: pnpm install

        #       - name: Build
        #         run: pnpm build

        #       - name: Deploy to Production
        #         env:
        #           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        #           VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        #           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        #         run: |
        #           pnpm dlx vercel deploy --prod --yes --token $VERCEL_TOKEN